apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  user: YWRtaW4=
  password: bTRRMm92STNDVA==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  user: YWRtaW4=
  password: OHpVZ3lLRTNxag==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: dGRqYmZJNm56NA==
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  access-key: bXNhLWZyYW1ld29yaw==
  secret-key: bXNhLWZyYW1ld29yay1taW5pbw==
