spring:
  application:
    name: parkingsk-member
  datasource:
    platform: mariadb
    # url: jdbc:mariadb://mariadb-url:3306/database
    url: jdbc:mariadb://factory-zdb-parkingsk-maria-mariadb.factory-zdb:3306/member
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  kafka:
    consumer:
      bootstrap-servers: factory-zdb-parkingsk-stream-kafka-0.factory-zdb-parkingsk-stream-kafka-headless.factory-zdb.svc.cluster.local:9092
      topic-name: BOOKING
      group-id: foo
domain:
  group: parkingsk
  name: member