spring:
  application:
    name: parkingsk-bff
  sleuth:
    trace-id128: true
    enabled: true
    http:
      enabled: true
    log:
      slf4j:
        enabled: true
    sampler:
      probability: 1.0    # Open Zipkin 으로 데이터를 전송하는 트랜잭션 샘플링 비율
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
#  session:
#    store-type: redis
#    redis:
#      flush-mode: on_save
#      save-mode: always
#      namespace: spring:test
#  redis:
#    port: 6379
#    host: localhost
#    password:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: 30
#    database: 0
api:
  bff:
    url: http://localhost:8080
  booking:
    url: http://localhost:8081
  member:
    url: http://localhost:8082
  parkinglot:
    url: http://localhost:8083
  review:
    url: http://localhost:8084

    
 