spring:
  application:
    name: parkingsk-parkinglot
  datasource:
    platform: mariadb
    # url: jdbc:mariadb://mariadb-url:3306/database
    url: jdbc:mariadb://factory-zdb-parkingsk-maria-mariadb.factory-zdb:3306/parkingLot
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  kafka:
    producer:
      bootstrap-servers: factory-zdb-parkingsk-stream-kafka-0.factory-zdb-parkingsk-stream-kafka-headless.factory-zdb.svc.cluster.local:9092
      topic-name: CAPACITY
      group-id: foo
  sleuth:
    traceId128: true
  sampler:
      probability: 1.0
domain:
  group: parkingsk
  name: parkinglot