apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - lifecycle:
          postStart:
            exec:
              command: null
            httpGet:
              path: /actuator/health
              port: 8091
          preStop:
            exec:
              command: null
            httpGet:
              path: /actuator/health
              port: 8091
        name: app
